apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "emr.name" . }}
  labels:
    {{- include "emr.labels" . | nindent 4 }}
data:
  ENACTOR_JMX_APPLICATIONID: ReportServer
  ENACTOR_RMI_SERVERHOST: {{ include "emr.name" . }}
  ENACTOR_SERVICE_DEFAULTSCHEDULEDJOBRUNTIMECONTEXT: Enactor Web Reports

  ENACTOR_MAXTOTAL: "300"
  ENACTOR_MAXTHREADS: "200"

  ENABLE_ENACTOR_SECONDARY_DATASOURCE: "false"
  ENACTOR_COMMON_REPORTS_DATASOURCENAME: java:comp/env/ENACTOR_SECONDARY_DATASOURCE
  ENACTOR_DB_SECONDARY_JDBC_URL: 'jdbc:mysql:\/\/REPLACE_DB_HOST:REPLACE_PORT\/REPLACE_DATABASE_NAME?useSSL=false\&amp;defaultFetchSize=1000\&amp;useCursorFetch=true\&amp;useLegacyDatetimeCode=false\&amp;serverTimezone=Europe%2FLondon\&amp;useUnicode=true\&amp;characterEncoding=UTF-8'
  ENACTOR_DB_SECONDARY_PASS: REPLACE_PASSWORD
  ENACTOR_DB_SECONDARY_USER: REPLACE_USERNAME
  ENACTOR_SECONDARY_MAXIDLE: "200"
  ENACTOR_SECONDARY_MAXTOTAL: "300"

  JMPS: 128m
  JXMS: 1024m
  JXMX: 5120m
