apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "emp.name" . }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
data:
  ENACTOR_JMX_APPLICATIONID: ProcServer
  ENACTOR_JMX_MANAGEMENTNODEHOSTNAME: localhost
  ENACTOR_MAXTHREADS: "250"

  JXMS: 1024m
  JXMX: 5120m
