apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "tms.name" . }}
  labels:
    {{- include "tms.labels" . | nindent 4 }}
data:
  ENACTOR_JMX_APPLICATIONID: TmsServer
  ENACTOR_MODULES_TMS: "true"
