apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "emp.name" . }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
data:
  ENACTOR_JMX_APPLICATIONID: ProcServer
  ENACTOR_BROADCAST_DEFAULTDOWNLOADSERVERHOSTNAME: http://{{ include "primary.ingress" . }}/
  ENACTOR_BROADCAST_DEFAULTDOWNLOADURL: http://{{ include "primary.ingress" . }}:{{ include "emp.http.port" . }}/WebCore/FileDownloadServlet
  ENACTOR_RMI_SERVERHOST: {{ include "primary.ingress" . }}
  ENACTOR_MAXTHREADS: "250"

  JXMS: 1024m
  JXMX: 5120m
