apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "emp.name" . }}
  labels:
    {{- include "ema.labels" . | nindent 4 }}
data:
  ENACTOR_BROADCAST_DEFAULTDOWNLOADSERVERHOSTNAME: http://{{ .Values.dns.emp }}.{{ .Values.dns.domain }}/
  ENACTOR_BROADCAST_DEFAULTDOWNLOADURL: http://{{ .Values.dns.emp }}.{{ .Values.dns.domain }}:{{ include "emp.http.port" . }}/WebCore/FileDownloadServlet
#  ENACTOR_JMX_APPLICATIONID: ProcServer
  ENACTOR_JMX_MANAGEMENTNODEHOSTNAME: localhost
  ENACTOR_TOMCAT_HTTP_DISABLED: "false"
  JXMX: "768m"