{{- range $name, $comp := .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include (printf "%s.labels" $name) $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    {{- include "service.ports" (index $.Values.network $name) | nindent 4 }}
  selector:
    {{- include (printf "%s.selectorLabels" $name) $ | nindent 4 }}
{{- end }}
