{{- range $name, $comp := .Values.components }}
{{- $repo := $comp.repository | default $.Values.image.repository }}
{{- $image := printf "%s/%s" $repo $comp.image | clean }}
{{- $svc := "" }}
{{- $port := "" }}
{{- if $comp.dependsOn.component }}
{{- $svc = include (printf "%s.name" $comp.dependsOn.component) $ }}
{{- $port = index $.Values.network $comp.dependsOn.component "http" }}
{{- else }}
{{- $svc = $comp.dependsOn.service }}
{{- $port = $comp.dependsOn.port }}
{{- end }}
{{- $dependency := dict "dependsOn" $.Values.global.dependsOn "service" $svc "port" $port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels:
    {{- include (printf "%s.labels" $name) $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include (printf "%s.selectorLabels" $name) $ | nindent 6 }}
  serviceName: {{ $name }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        checksum/common: {{ include (print $.Template.BasePath "/configmap-common.yaml") $ | sha256sum }}
        checksum/{{ $name }}: {{ include (print $.Template.BasePath "/configmap-" $name ".yaml") $ | sha256sum }}
        {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include (printf "%s.selectorLabels" $name) $ | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 300

      initContainers:
        {{ include "dependsOn" $dependency | nindent 8 }}

      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $image }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{ include "db.env" $ | nindent 12 }}

            - name: ENACTOR_JMX_SERVERHOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: ENACTOR_RMI_SERVERHOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: ENACTOR_JMX_APPLICATIONID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          envFrom:
            - configMapRef:
                name: config-common
            - configMapRef:
                name: config-{{ $name }}
            - secretRef:
                name: secret-common
          ports:
            {{- range $comp.containerPorts }}
            - name: {{ . }}
              containerPort: {{ index $.Values.network $name . }}
              protocol: TCP
            {{- end }}
          {{- with $comp.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.probes.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.probes.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}

          volumeMounts:
            - name: apphome
              mountPath: /enactor/app/home

      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: apphome
      spec:
        storageClassName: {{ $.Values.storage.storageClass }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.storage.size }}
{{- end }}
