apiVersion: v2
name: enactor-pdp
description: Enactor PDP-server

type: application

version: 0.1.0
appVersion: "1.0"

maintainers: 
  - name: Hans Brinck
    email: hans.brinck@lindex.com

home: https://github.com/enactor-customer-oss/enactor-charts

dependencies:
  - name: mariadb
    version: "11.4.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.deploy