{{ if .Values.pdp.instances }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pdp
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.pdp.env }}
  {{ .Values.pdp.env | toYaml }}
  {{- end }}
  ENACTOR_PDPMESSAGEFACTORY_CLASSNAME: com.enactor.coreUI.web.PDP.json.messages.PDPMixedModeMessageFactory
  ENACTOR_PDPPAGEELEMENTHANDLERFACTORY_CLASSNAME: com.enactor.coreUI.web.PDP.json.pageElementHandlers.PDPJsonPageElementHandlerFactory
  ENACTOR_PDPPROMPTFACTORY_CLASSNAME: com.enactor.coreUI.web.PDP.json.PDPMixedModePromptFactory
  ENACTOR_AXIS2_USER: {{ .Values.pdp.axis2.user }}
  ENACTOR_COMMON_APPLICATIONHOME: /enactor/app/home
  ENACTOR_COMMON_APPLICATIONDATAHOME: /enactor/app/home/data
  ENACTOR_COMMON_DATABASESCHEMA: {{ .Values.mariadb.auth.database }}
  ENACTOR_COMMON_DATASOURCENAME: "java:comp/env/ENACTOR_DATASOURCE"
  ENACTOR_COMMON_DS: "java:comp\\/env\\/ENACTOR_DATASOURCE"
  ENACTOR_COMMON_LICENCEFILENAME: /enactor/shared/licence/licence.xml
  ENACTOR_COMMON_PARENTPROCESSSET: {{ .Values.estate.common.parentProcessSet }}
  ENACTOR_COMMON_PROCESSSET: {{ .Values.estate.common.processSet }}
  ENACTOR_COMMON_USEPAYMENTSERVICE: "false"
  ENACTOR_DB_DRIVERCLASSNAME: com.mysql.jdbc.Driver
  ENACTOR_DB_JDBC_URL: {{ include "mariadb.jdbc.quotes" . | quote}}
  ENACTOR_DB_USER: {{ .Values.mariadb.auth.username }}
  ENACTOR_DEVICETYPE_PDPSERVER: PDP_SERVER
  ENACTOR_JMX_MANAGEMENTNODEHOSTNAME: {{ .Values.estate.jmx.name }}
  ENACTOR_JMX_MANAGEMENTNODEPORT: {{ .Values.estate.jmx.port | quote }}
  ENACTOR_JMX_SERVERHOSTNAME: localhost
  ENACTOR_MODULES_ORDERMODULE: "false"
  ENACTOR_MODULES_REPAIRMODULE: "false"
  ENACTOR_PROCESSCONNECTIONS_DEFINITIONID: {{ .Values.estate.common.processDefinitionID }}
{{- if .Values.estate.react.contentURL }}
  ENACTOR_REACTPOS_CONTENTURL: {{ .Values.estate.react.contentURL }}
{{- end }}
  ENACTOR_RMI_SERVERHOST: localhost
  ENACTOR_RMI_SERVERPORT: "39847"
  ENACTOR_RMI_SERVERSERVICEPORTALLOCATIONTIMEOUT: "3600"
  ENACTOR_RMI_SERVERSERVICEPORTS: ""
  ENACTOR_RMI_USESERVERSERVICEPORTS: "false"
  ENACTOR_ROOT: /enactor/app
  ENACTOR_SERVER_EMAPP_URL_BASE: {{ .Values.estate.ema }}
  ENACTOR_SERVER_EMPROC_URL_BASE: {{ .Values.estate.emp }}
  ENACTOR_SERVER_EMWS_URL_BASE: {{ .Values.estate.ems }}
  ENACTOR_SERVICE_DEFAULTSCHEDULEDJOBRUNTIMECONTEXT: Enactor PDP Server
  ENACTOR_SERVICE_DEVICETYPE: PDP_SERVER
  ENACTOR_SERVICE_LOCATIONID: "{{ .Values.store.number }}"
  ENACTOR_TRUSTSTORE_FILEPATH: /enactor/app/custom/trust
  PDPPORT: "39901"
  PROCESS_PERFORMANCE_LOG_LEVEL: "1"
  DATABASE_PERFORMANCE_LOG_LEVEL: "1"
{{- end }}
