{{ if .Values.pdc.instances }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pdc
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.pdc.env }}
  {{ .Values.pdc.env | toYaml | nindent 2 }}
  {{- end }}
  ENACTOR_PDC_DATABASE_LOCATION: /enactor/pdc/database/pdc/
  ENACTOR_PDC_TMS_HOST: {{ .Values.estate.tms.name | quote }}
  ENACTOR_PDC_TMS_PORT: {{ .Values.estate.tms.port | quote }}
  ENACTOR_PDC_COMPANY_NAME: {{ .Values.company.name | quote }}
  ENACTOR_COMMON_LICENSE_FILENAME: /enactor/pdc/licence/licence.xml
  ENACTOR_DEVICE_TYPE: PAYMENT_SERVICE
  ENACTOR_APPLICATION: /enactor
  ENACTOR_HOME: /enactor/home
  ENACTOR_ROOT: /enactor
{{- end }}
