{{- $root := . }}
{{- range $pos := .Values.pdc.instances }}
  {{- if eq .platform $root.Values.global.platform }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .id }}
  labels:
    {{- include "pdc.selectorLabels" . | nindent 4 }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: 7776
      targetPort: pdc-7776
      protocol: TCP
      name: pdc-7776
      {{- if eq $root.Values.service.type "NodePort" }}
      nodePort: {{ .port }}
      {{- end }}
    - port: 7777
      targetPort: pdc-7777
      protocol: TCP
      name: pdc-7777
  selector:
    {{- include "pdc.selectorLabels" . | nindent 4 }}
  {{- end }}
{{- end }}