{{- $root := . }}
{{- $basepath := .Template.BasePath }}
{{- range $pos := .Values.pdp.instances }}
  {{- if eq .platform $root.Values.pdp.platform }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .id }}
  labels:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
spec:
  type: {{ $root.Values.pdp.serviceType }}
  ports:
    - port: 39901
      targetPort: pdp-http
      protocol: TCP
      name: http
      {{- if eq $root.Values.pdp.serviceType "NodePort" }}
      nodePort: {{ $root.Values.pdp.nodePort }}
      {{- end }}
  {{- range $name,$port := $root.Values.pdp.ports }}
    - port: {{ $port }}
      protocol: TCP
      targetPort: {{ $name }}
      name: {{ $name }}
      {{- if eq $root.Values.pdp.serviceType "NodePort" }}
      nodePort: {{ $port }}
      {{- end }}
  {{- end}}
  selector:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
  {{- end }}
{{- end }}