{{- $root := . }}
{{- $basepath := .Template.BasePath }}
{{- range $pos := .Values.pdp.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: pdp-{{ .id }}
  labels:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 39901
      targetPort: pdp-http
      protocol: TCP
      name: http
  selector:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
{{- end }}