{{- $root := . }}
{{- $basepath := .Template.BasePath }}
{{- range $pos := .Values.pdp.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .id }}
  labels:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 39901
      targetPort: pdp-http
      protocol: TCP
      name: http
  {{- range $name,$port := $root.Values.pdp.ports }}
    - port: {{ $port }}
      protocol: TCP
      targetPort: {{ $name }}
      name: {{ $name }}
  {{- end}}
  selector:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
{{- end }}