{{- $root := . }}
{{- $basepath := .Template.BasePath }}
{{- range $pos := .Values.pdp.instances }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pdp-{{ .id }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "common.selectorLabels" $root | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pdp.selectorLabels" . | nindent 6 }}
  replicas: {{ $root.Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "pdp.selectorLabels" . | nindent 8 }}
        {{- include "common.selectorLabels" $root | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-pdp.yaml") $root | sha256sum }}
        {{- if $root.Values.features.argocdSyncwaves.enabled }}
        argocd.argoproj.io/sync-wave: {{ $root.Values.features.argocdSyncwaves.waves.pdp | default 10 | quote }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 15
      serviceAccountName: {{ include "pdp.serviceAccountName" $root }}
      {{- if $root.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $name := $root.Values.imagePullSecrets }}
        - name: {{ $name }}
      {{- end }}
      {{- end }}

      {{ if $root.Values.pdp.priorityClassName -}}
      priorityClassName: {{ $root.Values.pdp.priorityClassName }}
      {{- end }}
      {{ if $root.Values.pdp.affinity -}}
      affinity:
        {{- toYaml $root.Values.pdp.affinity | nindent 8 }}
      {{- end }}

      {{ if $root.Values.pdp.securityContext -}}
      securityContext:
        {{- toYaml $root.Values.pdp.securityContext | nindent 8 }}
      {{- end }}

      {{ if $root.Values.pdp.nodeName -}}
      nodeName: {{ $root.Values.pdp.nodeName }}
      {{- end }}
      {{ if $root.Values.pdp.nodeSelector -}}
      nodeSelector:
        {{- toYaml $root.Values.pdp.nodeSelector | nindent 8 }}
      {{- end }}

      enableServiceLinks: false

      initContainers:
        - name: verifydb
          image: busybox:1.31
          command: 
            - 'sh'
            - '-c'
            - |-
              echo -e "Checking for the availability of MySQL Server deployment '$SERVERNAME'";
              while ! nc -z $SERVERNAME 3306;
                do sleep 2;
                printf "-";
              done;
              echo -e "  >> MySQL DB Server '$SERVERNAME' has started";
          env:
            - name: SERVERNAME
              value: {{ template "dbserver" $root }}

      containers:
        - name: pdp
          image: {{ include "image" $root.Values.pdp.image }}
          imagePullPolicy: {{ $root.Values.pdp.image.pullPolicy  }}
          ports:
            - containerPort: 39901
              name: pdp-http
            - containerPort: 53311
              name: pdp-https
#            - containerPort: 39847
#              name: jmx
#            - containerPort: 39848
#              name: pdp-jmx
            - containerPort: 8080
              name: health
          {{- range $name,$port := $root.Values.pdp.ports }}
            - containerPort: {{ $port }}
              name: {{ $name }}
          {{- end}}

          startupProbe:
            tcpSocket:
              port: 39901
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30

          livenessProbe:
#            httpGet:
#              path: /live
#              port: health
            tcpSocket:
              port: 39901
#            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
#            httpGet:
#              path: /ready
#              port: health
            tcpSocket:
              port: 39901
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3

          env:
            {{- include "env.defaults" $root | nindent 12 }}
            {{- include "env.pdp" $root | nindent 12 }}
            - name: ENACTOR_CONTAINER_DEVICEID
              value: {{ .hostId | quote }}
            - name: ENACTOR_JMX_APPLICATIONID
              value: {{ .hostId | quote }}
            - name: ENACTOR_SERVICE_DEVICEID
              value: {{ .hostId | quote }}
            {{- range $key, $val := $root.Values.pdp.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: config-common
                
            - configMapRef:
                name: config-{{ $root.Values.pdp.name }}

            - secretRef:
                name: secret-common

          {{- if $root.Values.pdp.resources }}
          resources: {{- toYaml $root.Values.pdp.resources | nindent 12 }}
          {{- end }}

          volumeMounts: {{ if $root.Values.pdp.extraVolumeMounts }}{{ toYaml $root.Values.pdp.extraVolumeMounts | nindent 12 }}{{ end }}
            - name: pdp-home
              mountPath: /enactor/app/home
            - name: truststore
              mountPath: /enactor/app/custom/trust

        {{ if $root.Values.pdp.extraContainers }}
        {{- toYaml $root.Values.pdp.extraContainers | nindent 8 }}
        {{- end }}

      volumes:
        - name: truststore
          secret:
            secretName: {{ $root.Values.truststore.certSecret }}
        {{- if $root.Values.pdp.extraConfigmapMounts }}
        {{- toYaml $root.Values.pdp.extraConfigmapMounts | nindent 8 }}
        {{- end }}
      
  volumeClaimTemplates:
    - metadata:
        name: pdp-home
      spec:
        storageClassName: {{ $root.Values.pdp.persistence.storageClass }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $root.Values.pdp.persistence.size }}
{{- end }}