{{- $root := . }}
{{- $basepath := .Template.BasePath }}
{{- range $pos := .Values.pdc.instances }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pdc-{{ .id }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "common.selectorLabels" $root | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pdc.selectorLabels" . | nindent 6 }}
  replicas: {{ $root.Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "pdc.selectorLabels" . | nindent 8 }}
        {{- include "common.selectorLabels" $root | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $basepath "/configmap-pdc.yaml") $root | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 15
      serviceAccountName: {{ include "pdc.serviceAccountName" $root }}
      {{- if $root.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $name := $root.Values.imagePullSecrets }}
        - name: {{ $name }}
      {{- end }}
      {{- end }}

      {{ if $root.Values.pdc.priorityClassName -}}
      priorityClassName: {{ $root.Values.pdc.priorityClassName }}
      {{- end }}
      {{ if $root.Values.pdc.affinity -}}
      affinity:
        {{- toYaml $root.Values.pdc.affinity | nindent 8 }}
      {{- end }}

      {{ if $root.Values.pdc.securityContext -}}
      securityContext:
        {{- toYaml $root.Values.pdc.securityContext | nindent 8 }}
      {{- end }}
      
      {{ if $root.Values.pdc.nodeName -}}
      nodeName: {{ $root.Values.pdc.nodeName }}
      {{- end }}
      {{ if $root.Values.pdc.nodeSelector -}}
      nodeSelector:
        {{- toYaml $root.Values.pdc.nodeSelector | nindent 8 }}
      {{- end }}

      enableServiceLinks: false

      containers:
        - name: pdc
          image: {{ include "image" $root.Values.pdc.image }}
          imagePullPolicy: {{ $root.Values.pdc.image.pullPolicy  }}
          ports:
            #- containerPort: 8080
            #  name: pdc-http
            #- containerPort: 2099
            #  name: pdc-2099
            #- containerPort: 7775
            #  name: pdc-7775
            - containerPort: 7776
              name: pdc-7776
            - containerPort: 7777
              name: pdc-7777
          env:
            {{- include "env.defaults" $root | nindent 12 }}
            {{- include "env.pdc" $root | nindent 12 }}
            - name: ENACTOR_PD_HOST_ID
              value: {{ .hostId | quote }}
            {{- range $key, $val := $root.Values.pdc.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}

          envFrom:
            - configMapRef:
                name: config-common
                
            - configMapRef:
                name: config-{{ $root.Values.pdc.name }}

          {{- if $root.Values.pdc.resources }}
          resources: {{- toYaml $root.Values.pdc.resources | nindent 12 }}
          {{- end }}

          volumeMounts: {{ if $root.Values.pdc.extraVolumeMounts }}{{ toYaml $root.Values.pdc.extraVolumeMounts | nindent 12 }}{{ end }}
            - name: pdc-db
              mountPath: /enactor/pdc/database

        {{- if $root.Values.pdc.extraContainers }}
        {{- toYaml $root.Values.pdc.extraContainers | nindent 8 }}
        {{- end }}

      {{- if $root.Values.pdc.extraConfigmapMounts }}
      volumes:
        {{- toYaml $root.Values.pdc.extraConfigmapMounts | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: pdc-db
      spec:
        storageClassName: {{ $root.Values.pdc.persistence.storageClass }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $root.Values.pdc.persistence.size }}
{{- end }}