# Default values for enactor-pdp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  platform: k8s

features:
  argocdSyncwaves:
    enabled: false
    waves:
      pdp: 10
      pdc: 20

dns:
  domain: my.fqdn.address
  ems: ems
  ema: ema
  emp: emp

store:
  number: null # The store-id
  name: null # The name of the store
  country: null

company:
  name: null # The name of the company

labels: {}

estate:
  ema: http://ema.backend
  emp: http://emp.backend
  ems: http://ems.backend
  jmx: 
    name: ems.backend
    port: 39847
  tms:
    name: ems.backend
    port: 39888

  common:
    processSet: NextGen
    parentProcessSet: ""
    processDefinitionID: ""

  react:
    contentURL: null

truststore:
  certSecret: truststore
  pwdSecret: truststore-pwd

java:
  country: SE
  language: en
  timezone: Europe/Stockholm

pdp:
  name: pdp
  enabled: true
  axis2:
    user: admin
  image:
    repository: enactorpdp
    tag: latest
    tag_override:
    pullPolicy: Always
  env: {}
  persistence:
    storageClass: null
    size: "10Gi"
  ports:
    jmx-server: 39847
    jmx-service: 39848
  resources:
    ## Example:
    ## limits:
    ##    cpu: 0.5
    ##    memory: 256Mi
    limits: {}
    ## Examples:
    ## requests:
    ##    cpu: 0.5
    ##    memory: 256Mi
    requests: {}
  extraVolumeMounts: []
  extraConfigmapMounts: []
  affinity: null
  securityContext: null
  nodeName: null
  nodeSelector: {}

pdc:
  name: pdc
  enabled: true
  image:
    repository: enactorpdp
    tag: latest
    tag_override:
    pullPolicy: Always
  env: {}
  persistence:
    storageClass: null
    size: "10Gi"
  resources:
    ## Example:
    ## limits:
    ##    cpu: 0.5
    ##    memory: 256Mi
    limits: {}
    ## Examples:
    ## requests:
    ##    cpu: 0.5
    ##    memory: 256Mi
    requests: {}
  extraVolumeMounts: []
  extraConfigmapMounts: []
  affinity: null
  securityContext: null
  nodeName: null
  nodeSelector: {}

extraObjects: []

# image:
#   repository: nginx
#   pullPolicy: IfNotPresent
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Thirdparty Configuration
mariadb:
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
    tag: 10.6.20-debian-12-r1
  fullnameOverride: mariadb
  deploy: true
  auth:
    database: "enactorpdp"
    username: "enactor"
    existingSecret: db-secrets
  primary:
    persistence:
      size: "25Gi"
      storageClass: null
    configuration: |
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log

      slow_query_log=0
      slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
      long_query_time=10.0

      character-set-server  = utf8mb4
      collation-server      = utf8mb4_general_ci
      transaction_isolation = READ-COMMITTED
      lower_case_table_names = 1

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    
replicas: 1