apiVersion: v2
name: enactor-em
description: Enactor EM-servers

type: application

version: 0.5.11
appVersion: "1.0"

maintainers:
  - name: Hans Brinck
    email: hans.brinck@lindex.com
  - name: Olof Spetz
    email: olof.spetz@lindex.com

home: https://github.com/enactor-customer-oss/enactor-charts

dependencies:
  - name: mariadb
    version: "11.4.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.deploy