apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pdp.name }}
  labels:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 39901
      targetPort: pdp-http
      protocol: TCP
      name: http
  selector:
    {{- include "pdp.selectorLabels" . | nindent 4 }}
