{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pdp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "pdp.selectorLabels" . | nindent 6 }}
automountServiceAccountToken: false
{{- end }}
