{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pdp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
{{- end }}
