{{ if .Values.pdc.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.pdc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "pdc.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "pdc.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-pdc.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "pdc.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $name := .Values.imagePullSecrets }}
        - name: {{ $name }}
      {{- end }}
      {{- end }}

      enableServiceLinks: false

      # securityContext:
      #     runAsUser: 1100
      #     runAsGroup: 1100
      #     fsGroup: 1100

      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "localhost"
            - "{{ .Values.pdc.name }}"

      containers:
        - name: pdc
          image: {{ .Values.pdc.image.repository }}:{{ .Values.pdc.image.tag | default  "latest" }}
          imagePullPolicy: {{ .Values.pdc.image.pullPolicy  }}
          ports:
            - containerPort: 8080
              name: pdc-http
            - containerPort: 2099
              name: pdc-2099
            - containerPort: 7776
              name: pdc-7706
            - containerPort: 7777
              name: pdc-7777
          env:
            {{- include "env.defaults" . | nindent 12 }}
            {{- include "env.pdc" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: config-{{ .Values.pdc.name }}

          # readinessProbe:
          #   httpGet:
          #     path: /WebMaintenance/
          #     port: 39830

          volumeMounts:
            - name: pdc-db
              mountPath: /enactor/pdc/database
            # - name: enactor-config
            #   mountPath: /enactor/app/config/enactor.xml
            #   subPath: enactor.xml

      volumes:
      #   - name: keystore
      #     secret:
      #       secretName: {{ .Release.Name }}-keystore
        # - name: enactor-config
        #   configMap:
        #     name: {{ .Release.Name }}-enactor-config
      
  volumeClaimTemplates:
    - metadata:
        name: pdc-db
      spec:
        storageClassName: {{ .Values.pdc.persistence.storageClass }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.pdc.persistence.size }}
{{- end }}